kind = "web"
previewPath = "/"
title = "WALLPAPER.MINIMAL"
version = "1.0.0"
id = "artifacts/wallpaper-minimal"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19491

[services.development]
run = "pnpm --filter @workspace/wallpaper-minimal run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wallpaper-minimal", "run", "build" ]
publicDir = "artifacts/wallpaper-minimal/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19491"
BASE_PATH = "/"
